/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyJniFunc */

#ifndef _Included_MyJniFunc
#define _Included_MyJniFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyJniFunc
 * Method:    Decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_MyJniFunc_Decrypt
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
